version: '3.1'
services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8000:80"
      - "8443:443"
    depends_on:
      - php
    volumes:
      - ./suuon/www:/icedata/suuon/www
      - ./services/nginx/config:/etc/nginx/conf.d
    container_name: nginx
  php:
    image: php-fpm:latest
    restart: always
    volumes:
      - ./suuon/www:/icedata/suuon/www
    container_name: php
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - "3326:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "suuon_db"
      MYSQL_USER: "suuon"
      MYSQL_PASSWORD: "suuon"
    volumes:
      - ./suuon/database:/var/lib/mysql
    container_name: mariadb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8001:80"
    environment:
      PMA_HOST: "db"
      PMA_USER: "app"
      PMA_PASSWORD: "123123"
